name: Release Charts

on: push

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "bagnaram"
          git config user.email "bagnaram@users.noreply.github.com"
                - name: Add Helm Repositories

      - run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add openfga https://openfga.github.io/helm-charts
          helm repo update

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
